[package]
name = "nets-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
nets = { path = "../nets" }
clap = { version = "4", features = ["derive"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
hex = "0.4"

[[bin]]
name = "nets"
path = "src/main.rs"